// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Event: typeof import('./src/components/Event.vue')['default']
    Events: typeof import('./src/components/Events.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    Hero: typeof import('./src/components/Hero.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    Picture: typeof import('./node_modules/@islands/images/src/Picture.vue')['default']
  }
}

export { }
